### PR TITLE
Fix #24 failing tests

### PR DESCRIPTION
**Pull request by jwambugu**
When running the tests, the `test_b2c` test was failing if an error occurred running the test which may be 4xx or 5xx errors from mpesa. 

This PR will exit if an error occurs but checks if we received any response. In the future it might be better to check the error code to assert where it's a client or server error.

### CODE REVIEW

**Comment by gathuku** [comment]
@jwambugu Thank you for this fix, Can we change the CI to run tests on PHP `8.0` instead of `7.4`
https://github.com/gathuku/laravel_mpesa/blob/cc61d3494e059544e36949a752deec026f25e311/.github/workflows/run_tests.yml#L13

**Comment by jwambugu** [comment]
For now we can leave it at `7.4`. 

Running the tests locally `php  8.0.9` prints a warning `Error:  This version of PHPUnit does not support code coverage on PHP 8`  which I think needs an update of `phpunit` to `^9.0` which requires `php: >=7.3` as of version [9.5.10](https://packagist.org/packages/phpunit/phpunit#9.5.10)

The minimum version for this package is `7.1` which might break changes when run on  `php: < 7.3`

**Comment by gathuku** [comment]
Thank you @jwambugu

**Comment by gathuku** [comment]
I have added a new release https://github.com/gathuku/laravel_mpesa/releases/tag/v1.2.2

**Pull request merged**
